<a href="https://colab.research.google.com/github/zhihaohaoran/nerf/blob/main/depth_taros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install Miniconda
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
!bash /tmp/miniconda.sh -bfp /usr/local

# Initialize Conda
import os
os.environ['PATH'] = "/usr/local/bin:" + os.environ['PATH']
!conda update -n base -c defaults conda -y
!source /usr/local/etc/profile.d/conda.sh


--2024-12-13 22:57:57--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.32.241, 104.16.191.158, 2606:4700::6810:20f1, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.32.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 148337011 (141M) [application/octet-stream]
Saving to: ‘/tmp/miniconda.sh’

/tmp/miniconda.sh   100%[===================>] 141.46M   401MB/s    in 0.4s    

2024-12-13 22:57:58 (401 MB/s) - ‘/tmp/miniconda.sh’ saved [148337011/148337011]

PREFIX=/usr/local
Unpacking payload ...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directorie

In [ ]:
%cd /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis

/content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis


In [ ]:
!git clone https://github.com/DepthAnything/Depth-Anything-V2

Cloning into 'Depth-Anything-V2'...
remote: Enumerating objects: 136, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 136 (delta 41), reused 34 (delta 34), pack-reused 65 (from 1)
Receiving objects: 100% (136/136), 45.17 MiB | 15.94 MiB/s, done.
Resolving deltas: 100% (44/44), done.


In [1]:
%cd /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/Depth-Anything-V2

/content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/Depth-Anything-V2


In [3]:
!pip install -r requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 48.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 99.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 MB 101.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.4/906.4 MB 41.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 51.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 103.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 106.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 44.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 63.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 100.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 98.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:

import os

# Specify the path to the folder containing the images
folder_path = '/Users/liiuhaoran/Downloads/Scaffold-GS-main/gp_vis/lego/train'

# Get all the files in the folder
file_list = os.listdir(folder_path)

# Filter to include only files that have a .png extension (ignore other file types)
image_files = [file for file in file_list if file.endswith('.png')]

# Sort the files based on their current names
image_files.sort()

# Rename files starting from 000000.png
for idx, old_filename in enumerate(image_files):
    # Create the new filename with zero-padding
    new_filename = f"{idx:06}.png"

    # Construct full file paths
    old_file_path = os.path.join(folder_path, old_filename)
    new_file_path = os.path.join(folder_path, new_filename)

    # Rename the file
    os.rename(old_file_path, new_file_path)

print(f"Renamed {len(image_files)} files in {folder_path}")


In [ ]:
!python /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/Depth-Anything-V2/run.py --encoder vitl --img-path /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/gp_vis/lego/train_images --outdir /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/gp_vis/lego/depth_lego --pred-only

Streaming output truncated to the last 5000 lines.
  [ 66   1 158]]]
3
Progress 3/100: /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/gp_vis/lego/train_images/000002.png
[[[164 208 139]
  [164 208 139]
  [164 208 139]
  ...
  [152 244 227]
  [155 238 213]
  [159 229 192]]

 [[164 207 137]
  [164 207 137]
  [164 208 139]
  ...
  [152 243 225]
  [153 241 220]
  [155 238 213]]

 [[164 207 137]
  [164 207 137]
  [164 208 139]
  ...
  [152 243 225]
  [152 243 225]
  [152 243 225]]

 ...

 [[ 78  62 213]
  [ 78  62 213]
  [ 78  62 213]
  ...
  [ 67   5 162]
  [ 67   5 162]
  [ 67   5 162]]

 [[ 78  60 211]
  [ 78  62 213]
  [ 78  60 211]
  ...
  [ 67   5 162]
  [ 67   5 162]
  [ 67   5 162]]

 [[ 78  60 211]
  [ 78  60 211]
  [ 78  60 211]
  ...
  [ 67   5 162]
  [ 66   3 160]
  [ 66   3 160]]]
3
Progress 4/100: /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/gp_vis/lego/train_images/000003.png
[[[164 207 137]
  [164 207 137]
  [164 207 137]
  ...
  [171 178  87]
  [173 17

In [ ]:
!python /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/Depth-Anything-V2/run.py --encoder vitl --img-path /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/gp_vis/lego/lego/train/r_0.png --outdir /content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/gp_vis/lego/lego/depth --pred-only

xFormers not available
xFormers not available
/content/drive/MyDrive/3dgs/3dgscream/Scaffold-GS/gp_vis/Depth-Anything-V2/run.py:36: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur

In [ ]:
#create ecodepth conda environment
# Install Miniconda
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
!bash /tmp/miniconda.sh -bfp /usr/local

# Initialize Conda
import os
os.environ['PATH'] = "/usr/local/bin:" + os.environ['PATH']
!conda update -n base -c defaults conda -y
!source /usr/local/etc/profile.d/conda.sh
%cd /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/EcoDepth
!conda env create -f env.yml

# Initialize Conda in the current shell session
!source /usr/local/etc/profile.d/conda.sh && conda activate ecodepth
%cd /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/EcoDepth/depth
!cp /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/EcoDepth/depth/quantize.py /usr/local/envs/ecodepth/lib/python3.11/site-packages/taming/modules/vqvae
!source activate ecodepth && pip install clip

--2024-04-19 10:43:37--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.32.241, 104.16.191.158, 2606:4700::6810:20f1, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.32.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 143351488 (137M) [application/octet-stream]
Saving to: ‘/tmp/miniconda.sh’

/tmp/miniconda.sh   100%[===================>] 136.71M   374MB/s    in 0.4s    

2024-04-19 10:43:37 (374 MB/s) - ‘/tmp/miniconda.sh’ saved [143351488/143351488]

PREFIX=/usr/local
Unpacking payload ...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directorie

In [ ]:
#run ecodepth
!source activate ecodepth && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/EcoDepth/depth/infer.py  --min_depth 1e-3 --no_of_classes 200 --ckpt_dir checkpoints/vkitti.ckpt
!source activate ecodepth && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/eval.py

/usr/local/envs/ecodepth/lib/python3.11/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels

Loading openai/clip-vit-large-patch14 to CLIPTextModel.....

Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel: ['vision_model.pre_layrnorm.weight', 'vision_model.encoder.layers.8.self_attn.out_proj.bias', 'vision_model.encoder.layers.17.ml

In [ ]:
#create zoe conda environment
#!conda env create -f env.yml
# Initialize Conda in the current shell session
#!source /usr/local/etc/profile.d/conda.sh && conda activate ecodepth
%cd /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/ZoeDepth-main/ZoeDepth-main
!conda env create -n zoe --file environment.yml
!source activate zoe && conda install pytorch torchvision torchaudio cudatoolkit=11.8.0 -c pytorch

/content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/ZoeDepth-main/ZoeDepth-main
Channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
Platform: linux-64
Solving environment: | / - \ | / done

pyparsing-3.1.2      | 87 KB     | :   0% 0/1 [00:00<?, ?it/s]
cuda-opencl-dev-12.5 | 87 KB     | :   0% 0/1 [00:00<?, ?it/s]

cuda-crt-dev_linux-6 | 79 KB     | :   0% 0/1 [00:00<?, ?it/s]


xorg-xproto-7.0.31   | 73 KB     | :   0% 0/1 [00:00<?, ?it/s]



libexpat-2.6.2       | 72 KB     | :   0% 0/1 [00:00<?, ?it/s]




kiwisolver-1.4.5     | 72 KB     | :   0% 0/1 [00:00<?, ?it/s]





cuda-nvprune-12.5.82 | 70 KB     | :   0% 0/1 [00:00<?, ?it/s]






attr-2.5.1           | 69 KB     | :   0% 0/1 [00:00<?, ?it/s]







libbrotlicommon-1.1. | 68 KB     | :   0% 0/1 [00:00<?, ?it/s]








libcusolver-dev-11.6 | 65 KB     | :   0% 0/1 [00:00<?, ?it/s]









libdeflate-1.17      | 63 KB     | :   0% 0/1 [00:00<?, ?it/s]










libzlib-1.2.13       | 6

In [ ]:
#run zoedepth and save depth map then run colmap and save depth map.
%cd /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/ZoeDepth-main/ZoeDepth-main
!source activate zoe && python sanity.py
#%cd /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/ZoeDepth-main
#!source activate zoe && python new_colmap_depth_map.py -i /content/drive/MyDrive/gzh_nerf/spin/spinnerf-dataset/10/undistorted/stereo/depth_maps --output_dir /content/drive/MyDrive/gzh_nerf/spin/spinnerf-dataset/10/undistorted/colmapdepthmap
#!source activate zoe && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/eval.py

/content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/ZoeDepth-main/ZoeDepth-main

EnvironmentNameNotFound: Could not find conda environment: zoe
You can list all discoverable environments with `conda info --envs`.




In [ ]:
#run zoedepth and save depth map then run colmap and save depth map.
!source activate zoe && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/Depth-Anything-main/Depth-Anything-main/run.py --encoder vitl --img-path /content/drive/MyDrive/gzh_nerf/spin/spinnerf-dataset/10/undistorted/images --outdir /content/drive/MyDrive/gzh_nerf/spin/spinnerf-dataset/10/undistorted/depthanythingmap --pred-only --grayscale
!source activate zoe && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/eval.py

xFormers not available
xFormers not available
Total parameters: 335.32M
  0% 0/100 [00:00<?, ?it/s]/content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/Depth-Anything-main/Depth-Anything-main/run.py:84: RuntimeWarning: divide by zero encountered in scalar divide
  print(np.max(depth)/np.min(depth))
inf
  1% 1/100 [00:02<03:39,  2.21s/it]inf
  2% 2/100 [00:04<04:02,  2.47s/it]inf
  3% 3/100 [00:06<03:39,  2.27s/it]inf
  4% 4/100 [00:07<02:33,  1.60s/it]inf
  5% 5/100 [00:08<02:17,  1.45s/it]inf
  6% 6/100 [00:09<02:05,  1.33s/it]inf
  7% 7/100 [00:10<01:40,  1.08s/it]inf
  8% 8/100 [00:10<01:24,  1.09it/s]inf
  9% 9/100 [00:11<01:13,  1.24it/s]inf
 10% 10/100 [00:12<01:06,  1.36it/s]inf
 11% 11/100 [00:12<01:00,  1.47it/s]inf
 12% 12/100 [00:13<00:57,  1.53it/s]inf
 13% 13/100 [00:14<01:21,  1.07it/s]inf
 14% 14/100 [00:15<01:23,  1.02it/s]inf
 15% 15/100 [00:16<01:23,  1.02it/s]inf
 16% 16/100 [00:18<01:29,  1.07s/it]inf
 17% 17/100 [00:18<01:15,  1.09it/s]inf
 18% 1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/eval.py

(2235, 3974)
(2235, 3974)
^C


In [ ]:
!source activate zoe && pip install scikit-image


In [ ]:

!source activate zoe && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/eval.py

(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)
(2232, 3970)

In [ ]:
!conda create -n uni11 python=3.11

Channels:
 - defaults
Platform: linux-64
Solving environment: - done

## Package Plan ##

  environment location: /usr/local/envs/uni11

  added / updated specs:
    - python=3.11


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_5 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.3.11-h06a4308_0 
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0 
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1 
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1 
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1 
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0 
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 
  openssl

In [ ]:
!source activate uni11 && pip install -e . --extra-index-url https://download.pytorch.org/whl/cu118


Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Obtaining file:///content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/UniDepth-main
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
  Using cached black-24.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (74 kB)
  Using cached blosc2-2.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
  Using cached botocore-1.34.54-py3-none-any.whl.metadata (5.7 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 9.8 MB/s eta 0:00:00
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cac

In [ ]:
#!source activate uni11 && conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
!source activate uni11 && python /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/UniDepth-main/scripts/demo.py

Torch version: 2.2.2
Downloading: "https://github.com/lpiccinelli-eth/unidepth/zipball/main" to /root/.cache/torch/hub/main.zip
Traceback (most recent call last):
  File "/content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/depth_estimation/UniDepth-main/scripts/demo.py", line 32, in <module>
    model = torch.hub.load(
            ^^^^^^^^^^^^^^^
  File "/usr/local/envs/uni11/lib/python3.11/site-packages/torch/hub.py", line 566, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/uni11/lib/python3.11/site-packages/torch/hub.py", line 592, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/uni11/lib/python3.11/site-packages/torch/hub.py", line 106, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module

In [ ]:
%cd /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/remove/nerf-object-removal-main

/content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/remove/nerf-object-removal-main


In [ ]:
!conda create -n object-removal python=3.8

Channels:
 - defaults
Platform: linux-64
Solving environment: | done

## Package Plan ##

  environment location: /usr/local/envs/object-removal

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-23.3.1                 |   py38h06a4308_0         2.6 MB
    python-3.8.19              |       h955ad1f_0        23.8 MB
    setuptools-68.2.2          |   py38h06a4308_0         948 KB
    wheel-0.41.2               |   py38h06a4308_0         108 KB
    ------------------------------------------------------------
                                           Total:        27.4 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.3.11-h06a4308_0 
  ld_impl_linux-

In [ ]:
!unzip /content/drive/MyDrive/gzh_nerf/spin/ubuntu_data_depth/remove/data/data/nerf-object-removal.zip

Streaming output truncated to the last 5000 lines.
  inflating: nerf-object-removal/003/masks_synthetic/319.npy  
  inflating: nerf-object-removal/003/masks_synthetic/331.npy  
  inflating: nerf-object-removal/003/masks_synthetic/325.npy  
  inflating: nerf-object-removal/003/masks_synthetic/324.npy  
  inflating: nerf-object-removal/003/masks_synthetic/330.npy  
  inflating: nerf-object-removal/003/masks_synthetic/318.npy  
  inflating: nerf-object-removal/003/masks_synthetic/293.npy  
  inflating: nerf-object-removal/003/masks_synthetic/287.npy  
  inflating: nerf-object-removal/003/masks_synthetic/250.npy  
  inflating: nerf-object-removal/003/masks_synthetic/278.npy  
  inflating: nerf-object-removal/003/masks_synthetic/252.npy  
  inflating: nerf-object-removal/003/masks_synthetic/291.npy  
  inflating: nerf-object-removal/003/masks_synthetic/285.npy  
  inflating: nerf-object-removal/003/masks_synthetic/326.npy  
  inflating: nerf-object-removal/003/masks_synthetic/332.npy  
  in

In [ ]:

!python /content/drive/MyDrive/gzh_nerf/spin/SPIn-NeRF-master/evaluate_ouput.py

Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /usr/local/lib/python3.10/dist-packages/lpips/weights/v0.1/alex.pth
/content/drive/MyDrive/gzh_nerf/spin/SPIn-NeRF-master/evaluate_ouput.py:50: FutureWarning: `multichannel` is a deprecated argument name for `structural_similarity`. It will be removed in version 1.0. Please use `channel

In [ ]:
!ffmpeg -i /content/drive/MyDrive/gzh_nerf/spin/SPIn-NeRF-master/PAPER-RENDER-RESULTS/spinwithzoe.mp4 -vf "fps=7.25,scale=504:378" /content/drive/MyDrive/gzh_nerf/spin/SPIn-NeRF-master/PAPER-RENDER-RESULTS/spinwithzoeresult/output_frame_%04d.png

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab